In [1]:
from typing import List, Dict, Tuple, Set, Optional, Union, Any, Callable, Iterable
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
column_name = [
    'GlobalEventID',
            'Day',
            'MonthYear',
            'Year',
            'FractionDate',
            'Actor1Code',
            'Actor1Name',
            'Actor1CountryCode',
            'Actor1KnownGroupCode',
            'Actor1EthnicCode',
            'Actor1Religion1Code',
            'Actor1Religion2Code',
            'Actor1Type1Code',
            'Actor1Type2Code',
            'Actor1Type3Code',
            'Actor2Code',
            'Actor2Name',
            'Actor2CountryCode',
            'Actor2KnownGroupCode',
            'Actor2EthnicCode',
            'Actor2Religion1Code',
            'Actor2Religion2Code',
            'Actor2Type1Code',
            'Actor2Type2Code',
            'Actor2Type3Code',
            'IsRootEvent',
            'EventCode',
            'EventBaseCode',
            'EventRootCode',
            'QuadClass',
            'GoldsteinScale',
            'NumMentions',
            'NumSources',
            'NumArticles',
            'AvgTone',
            'Actor1Geo_Type',
            'Actor1Geo_FullName',
            'Actor1Geo_CountryCode',
            'Actor1Geo_ADM1Code',
            'Actor1Geo_Lat',
            'Actor1Geo_Long',
            'Actor1Geo_FeatureID',
            'Actor2Geo_Type',
            'Actor2Geo_FullName',
            'Actor2Geo_CountryCode',
            'Actor2Geo_ADM1Code',
            'Actor2Geo_Lat',
            'Actor2Geo_Long',
            'Actor2Geo_FeatureID',
            'DateAdded',
            'SourceURL'
        ]


data_df = pd.read_csv('gdfdata/230722.csv')

In [4]:
data_df.head()

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,Column13,Column14,Column15,Column16,Column17,Column18,Column19,Column20,Column21,Column22,Column23,Column24,Column25,Column26,Column27,Column28,Column29,Column30,Column31,Column32,Column33,Column34,Column35,Column36,Column37,Column38,Column39,Column40,Column41,Column42,Column43,Column44,Column45,Column46,Column47,Column48,Column49,Column50,Column51,Column52,Column53,Column54,Column55,Column56,Column57,Column58
0,1116435782,20220722,202207,2022,2022.5534,CAN,CANADA,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,20,20,2,1,3.0,13,2,13,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.85,-137.817,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
1,1116435783,20220722,202207,2022,2022.5534,CAN,CANADA,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,90,90,9,2,-2.0,13,2,13,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.85,-137.817,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
2,1116435784,20220722,202207,2022,2022.5534,CVL,COMMUNITY,NaN,NaN,NaN,NaN,NaN,CVL,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,20,20,2,1,3.0,7,2,7,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.85,-137.817,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
3,1116435785,20220722,202207,2022,2022.5534,CVL,COMMUNITY,NaN,NaN,NaN,NaN,NaN,CVL,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,90,90,9,2,-2.0,7,2,7,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.85,-137.817,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
4,1116435786,20220722,202207,2022,2022.5534,EDU,STUDENT,NaN,NaN,NaN,NaN,NaN,EDU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,110,110,11,3,-2.0,10,1,10,0.393701,3,"Loudoun County, Virginia, United States",US,USVA,39.0834,-77.6497,1480141,0,NaN,NaN,NaN,NaN,NaN,NaN,3,"Loudoun County, Virginia, United States",US,USVA,39.0834,-77.6497,1480141,20230722,https://www.loudountimes.com/news/school-board...

In [39]:
def transform_data(data:pd.DataFrame, column_name:List[str])->pd.DataFrame:
    duplicate_columns = [f'Column{i}' for i in range(43, 50)]
    for col in duplicate_columns:
        if col in data.columns:
            data.drop(col, axis=1, inplace=True)
    
    if len(data.columns) != len(column_name):
        raise ValueError('The number of columns is not equal to the number of column names')
    data.columns = [col.lower() for col in column_name]

    data['quadclass'] = data['quadclass'].replace({1:'Verbal Cooperation', 2:'Material Cooperation', 3:'Verbal Conflict', 4:'Material Conflict'})

    return data

def get_null_values(data:pd.DataFrame)->pd.DataFrame:
    null_values = data.isnull().sum()
    null_values = null_values[null_values > 0]
    null_values.sort_values(ascending=False, inplace=True)
    return null_values


def int_to_datetime(data:pd.DataFrame, column_name:str)->pd.DataFrame:
    data[column_name] = pd.to_datetime(data[column_name], format="%Y%m%d")
    return data

def get_date_range(df):
    min, max = df['Day'].min(), df['Day'].max()
    print('start_date: ', min, 'end_date: ', max)

def get_single_entity_group(df, *args):
    if len(args) > 3 or len(args) < 2:
        raise ValueError('The number of arguments is not equal to 3')
    if len(args) == 3: 
       entity1, entity2, idn= args[0], args[1], args[2]
       result = df.groupby([entity1, entity2])[idn].count().sort_values(ascending=False)
    else:
        entity, idn = args[0], args[1]
        result = df.groupby(entity)[idn].count().sort_values(ascending=False)
    print(result)

In [6]:
result_df = transform_data(data_df, column_name)
result_df = int_to_datetime(result_df, 'Day')
result_df.head()

,GlobalEventID,Day,MonthYear,Year,FractionDate,Actor1Code,Actor1Name,Actor1CountryCode,Actor1KnownGroupCode,Actor1EthnicCode,Actor1Religion1Code,Actor1Religion2Code,Actor1Type1Code,Actor1Type2Code,Actor1Type3Code,Actor2Code,Actor2Name,Actor2CountryCode,Actor2KnownGroupCode,Actor2EthnicCode,Actor2Religion1Code,Actor2Religion2Code,Actor2Type1Code,Actor2Type2Code,Actor2Type3Code,IsRootEvent,EventCode,EventBaseCode,EventRootCode,QuadClass,GoldsteinScale,NumMentions,NumSources,NumArticles,AvgTone,Actor1Geo_Type,Actor1Geo_FullName,Actor1Geo_CountryCode,Actor1Geo_ADM1Code,Actor1Geo_Lat,Actor1Geo_Long,Actor1Geo_FeatureID,Actor2Geo_Type,Actor2Geo_FullName,Actor2Geo_CountryCode,Actor2Geo_ADM1Code,Actor2Geo_Lat,Actor2Geo_Long,Actor2Geo_FeatureID,DateAdded,SourceURL
0,1116435782,2022-07-22,202207,2022,2022.5534,CAN,CANADA,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,20,20,2,1,3.0,13,2,13,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
1,1116435783,2022-07-22,202207,2022,2022.5534,CAN,CANADA,CAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,90,90,9,2,-2.0,13,2,13,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
2,1116435784,2022-07-22,202207,2022,2022.5534,CVL,COMMUNITY,NaN,NaN,NaN,NaN,NaN,CVL,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,20,20,2,1,3.0,7,2,7,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
3,1116435785,2022-07-22,202207,2022,2022.5534,CVL,COMMUNITY,NaN,NaN,NaN,NaN,NaN,CVL,NaN,NaN,CHRCTH,CATHOLIC,NaN,NaN,NaN,CHR,CTH,NaN,NaN,NaN,1,90,90,9,2,-2.0,7,2,7,-3.829401,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,4,"Pine Creek, Canada (general), Canada",CA,CA00,66.8500,-137.8170,-571329,20230722,https://www.chrisd.ca/2023/07/21/manitoba-firs...
4,1116435786,2022-07-22,202207,2022,2022.5534,EDU,STUDENT,NaN,NaN,NaN,NaN,NaN,EDU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,110,110,11,3,-2.0,10,1,10,0.393701,3,"Loudoun County, Virginia, United States",US,USVA,39.0834,-77.6497,1480141,3,"Loudoun County, Virginia, United States",US,USVA,39.0834,-77.6497,1480141,20230722,https://www.loudountimes.com/news/school-board...

In [22]:

result_2022_df = result_df[result_df['Year'] == 2022]
len(result_2022_df)

832

In [23]:
get_date_range(result_2022_df)

start_date:  2022-07-22 00:00:00 end_date:  2022-07-22 00:00:00

In [25]:
print( f'{len(result_2022_df)} rows in result_2022_df' )

832 rows in result_2022_df

In [40]:
get_single_entity_group(result_2022_df, 'Actor1Name', 'GlobalEventID')
# groupby(['Actor1Name'])['GlobalEventID'].count().sort_values(ascending=False)

Actor1Name
UNITED STATES                                    80
RUSSIA                                           28
PRESIDENT                                        16
UNITED KINGDOM                                   16
THE NETHERLAND                                   14
TAIWAN                                           12
PRIME MINISTER                                   11
POLICE                                           11
UTAH                                             11
CHINA                                            10
CANADA                                           10
SRI LANKA                                        10
UKRAINE                                           9
COMPANY                                           9
RUSSIAN                                           9
PRISON                                            9
PAKISTAN                                          8
FOREIGN SECRETARY                                 8
THE HAGUE                                         8
STUDENT                                           7
JUDGE                                             7
GOVERNMENT                                        7
VIETNAM                                           7
AUSTRALIA                                         7
UKRAINIAN                                         6
CONGRESS                                          6
TURKEY                                            6
DUTCH                                             6
IRANIAN                                           6
MOSCOW                                            6
SCHOOL                                            6
THE EU                                            6
EGYPT                                             6
WASHINGTON                                        6
MAHARASHTRA                                       5
KURD                                              5
RESIDENTS                                         5
RAJASTHAN                                         5
IRELAND                                           5
BRAZIL                                            4
MINIST                                            4
FRANCE                                            4
FRENCH                                            4
GEORGETOWN                                        4
GERMAN                                            4
INDONESIA                                         4
TAIPEI                                            4
A US                                              4
DELHI                                             4
TRINCOMALEE                                       4
COMMUNITY                                         4
COMMANDO                                          4
POPULATION                                        4
PARLIAMENT                                        4
BARACK OBAMA                                      4
THE US                                            3
HOUSTON                                           3
SRI LANKAN                                        3
TEXAS                                             3
SIOUX                                             3
INTELLIGENCE                                      3
SIKH                                              3
SECURITY COUNCIL                                  3
ITALY                                             3
RICHMOND                                          3
ISRAEL                                            3
TOURIST                                           3
KRITI                                             3
HAMBANTOTA                                        3
LABOR UNION                                       3
TRAVELER                                          3
MINORITY RIGHTS GROUP                             3
NETHERLANDS                                       3
PALESTINE                                         3
MAINE                                             3
AUSTRALIAN                                        3
FIGHTER                                           3
COMPANIES                                         3
DUTCH COURT                                       3
ARMY                                              3
ESTONIA                                           3
AMBASSADOR                                        3
EUROPEAN COMMISSION                               3
CALIFORNIA                                        3
GERMANY                                           3
GASTON BROWNE                                     3
INUIT                                             2
CRIMINAL                                          2
BEIJING                                           2
BARCELONA                                         2
OPPOSITION LEADER                                 2
BANK OF AMERICA                                   2
NORTH KOREA                                       2
NORTH CAROLINA                                    2
NEW ZEALAND                                       2
BANGLADESH                                        2
DOCTOR                                            2
THE UN                                            2
AZERBAIJAN                                        2
ZAMBIA                                            2
GHANA                                             2
PAPUA NEW GUINEA                                  2
BELARUS                                           2
ATAL BIHARI VAJPAYEE                              2
HOSPITAL                                          2
HANOI                                             2
STATE SUPREME COURT                               2
BRITAIN                                           2
CITIZEN                                           2
SPOKESMAN                                         2
PROSECUTOR                                        2
BUSINESS                                          2
CHEVRON                                           2
CATHOLIC                                          2
CARGO SHIP                                        2
CABINET                                           2
SAN FRANCISCO                                     2
SAUDI                                             2
MINISTRY                                          2
MYANMAR                                           2
GOVERNOR                                          2
UNITED NATIONS                                    2
EXXON                                             2
LAWYER                                            2
JUNTA                                             2
ASSOCIATION OF SOUTHEAST ASIAN NATIONS            2
LEGISLATOR                                        2
INTELLIGENCE COMMUNITY                            2
LITHUANIA                                         2
ACTOR                                             2
LONDON                                            2
MAGISTRATE                                        2
UNIVERSITY                                        2
ISTANBUL                                          2
YEMENI                                            2
MALE                                              2
JAKARTA                                           2
FLORIDA                                           2
MEDIA                                             2
MALAYSIA                                          2
YEMEN                                             2
WEST BENGAL                                       1
BULGARIAN                                         1
SECRETARY OF STATE                                1
SPAIN                                             1
SEPARATIST LEADER                                 1
BUREAUCRACY                                       1
SHANGHAI                                          1
VILLAGE                                           1
VIRGINIA                                          1
TRAVELLER                                         1
BRATISLAVA                                        1
AIR FORCE                                         1
SCIENTIST                                         1
TOURISM DEPARTMENT                                1
ZIMBABWE                                          1
THE WHITE HOUSE                                   1
ARBIL                                             1
AMSTERDAM                                         1
AMERICAN                                          1
ZHENGZHOU                                         1
AL QAEDA                                          1
TELEVISION                                        1
TATA MOTORS                                       1
UZBEKISTAN                                        1
TALIBAN                                           1
SUPREME COURT                                     1
SUICIDE BOMBER                                    1
BOSS                                              1
COLOMBO                                           1
SAN DIEGO                                         1
MADHYA PRADESH                                    1
MINIST OF EDUCATION                               1
ELECTION COMMISSION                               1
MILITARY                                          1
MIDI                                              1
MICHIGAN                                          1
MIAMI                                             1
MAYOR                                             1
ACCRA                                             1
MAGAZINE                                          1
MADRID                                            1
LEGISLATURE                                       1
EGYPTIAN                                          1
LAWMAKER                                          1
EUROPEAN                                          1
KURDISTAN                                         1
JORDAN                                            1
JAPANESE                                          1
FIRST STATE                                       1
FOREIGN CORRESPONDENT                             1
FRENCH POLYNESIA                                  1
IDAHO                                             1
IAEA                                              1
MINNESOTA                                         1
MURKOWSKI                                         1
CAPTAIN                                           1
POLITICAL PARTIES                                 1
ROSARIO                                           1
RALEIGH                                           1
CHIEF EXECUTIVE                                   1
QUEEN ELIZABETH II                                1
QATAR                                             1
PRODUCER                                          1
CHINESE                                           1
PRIEST                                            1
PRESIDENTIAL CANDIDATE                            1
COLLEGE                                           1
POLE                                              1
NAPOLI                                            1
POLAND                                            1
PHILIPPINE                                        1
PARLIAMENT HOUSE                                  1
PALESTINIAN                                       1
DEPUTIES                                          1
DISTRICT COURT                                    1
ORGANIZATION OF PETROLEUM EXPORTING COUNTRIES     1
OHIO                                              1
NEW YORK CITY                                     1
NETFLIX                                           1
ZIMBABWEAN                                        1
Name: GlobalEventID, dtype: int64

In [41]:
get_single_entity_group(result_2022_df, 'Actor1Name', 'Actor2Name', 'GlobalEventID')

# result_2022_df.groupby(['Actor1Name', 'Actor2Name'])['GlobalEventID'].count().sort_values(ascending=False)

Actor1Name                                     Actor2Name
THE NETHERLAND                                 UKRAINE                      11
UNITED STATES                                  UNITED STATES                10
RUSSIA                                         UKRAINE                       7
UNITED STATES                                  UKRAINE                       6
PRISON                                         THE HAGUE                     6
KURD                                           IRANIAN                       5
TAIWAN                                         TAIPEI                        5
RUSSIAN                                        ALGERIA                       5
PAKISTAN                                       UKRAINE                       5
IRANIAN                                        KURD                          5
FOREIGN SECRETARY                              JUNTA                         4
EGYPT                                          INDONESIA                     4
THE EU                                         ALGERIA                       4
RUSSIA                                         TAIPEI                        4
TRINCOMALEE                                    PRESIDENT                     4
PARLIAMENT                                     MILITARY                      4
INDONESIA                                      EGYPT                         4
TURKEY                                         ISRAEL                        4
UNITED STATES                                  CHINA                         4
CANADA                                         SCHOOL                        4
PRESIDENT                                      TRINCOMALEE                   4
GEORGETOWN                                     AIRLINE                       4
COMPANY                                        LABOR UNION                   3
TAIWAN                                         TAIWAN                        3
UNITED STATES                                  GOVERNMENT                    3
GOVERNMENT                                     UNITED STATES                 3
LABOR UNION                                    COMPANY                       3
HAMBANTOTA                                     SPY SHIP                      3
RAJASTHAN                                      MINIST OF WOMEN               3
FIGHTER                                        RUSSIAN                       3
FRANCE                                         ITALY                         3
RUSSIAN                                        VLADIMIR PUTIN                3
GASTON BROWNE                                  BRITAIN                       3
HOUSTON                                        TEXAS                         3
RUSSIA                                         PRISON                        3
THE HAGUE                                      PRISON                        3
RICHMOND                                       INDIANA                       2
POLICE                                         CHAMBER                       2
GERMANY                                        POLAND                        2
GERMAN                                         CLEVELAND                     2
INUIT                                          ROMAN CATHOLIC                2
INTELLIGENCE                                   KIEV                          2
FRENCH                                         MALI                          2
HANOI                                          TOURIST                       2
TURKEY                                         COMPANIES                     2
THE US                                         THE HAGUE                     2
THE HAGUE                                      THE US                        2
UKRAINE                                        MALAYSIA                      2
ISRAEL                                         TURKEY                        2
IRELAND                                        CONGRESS                      2
MALE                                           IDAHO                         2
SRI LANKA                                      NEW DELHI                     2
MYANMAR                                        FOREIGN SECRETARY             2
SRI LANKA                                      BEIJING                       2
MOSCOW                                         UNITED NATIONS                2
                                               UKRAINE                       2
                                               KIEV                          2
MINORITY RIGHTS GROUP                          GANG                          2
STUDENT                                        FLORIDA                       2
SPOKESMAN                                      UNIVERSITY                    2
SIOUX                                          UNITED STATES                 2
PAKISTAN                                       PAKISTAN                      2
TAIPEI                                         RUSSIA                        2
MALAYSIA                                       VIETNAM                       2
THE HAGUE                                      MALAYSIA                      2
MAINE                                          UNITED STATES                 2
MAHARASHTRA                                    STATE ASSEMBLY                2
MAGISTRATE                                     PRISON                        2
TAIPEI                                         TAIWAN                        2
LITHUANIA                                      BELARUS                       2
JUNTA                                          FOREIGN SECRETARY             2
JUDGE                                          POLICE                        2
PALESTINE                                      PRESIDENT                     2
SIKH                                           CIVILIAN                      2
ITALY                                          MONGOLIAN                     2
ISTANBUL                                       CARGO SHIP                    2
THE EU                                         UNITED STATES                 2
FOREIGN SECRETARY                              MYANMAR                       2
UKRAINE                                        THE NETHERLAND                2
                                               MOSCOW                        2
CHINA                                          UNITED STATES                 2
SAUDI                                          TOURIST                       2
UNITED STATES                                  POLICE                        2
CHEVRON                                        MARACAIBO                     2
CATHOLIC                                       SCHOOL                        2
CARGO SHIP                                     ISTANBUL                      2
UNITED STATES                                  ROYAL CARIBBEAN               2
PRIME MINISTER                                 VILLAGE                       2
UNITED STATES                                  THE WHITE HOUSE               2
CANADA                                         CATHOLIC                      2
CALIFORNIA                                     RESIDENTS                     2
CABINET                                        FRENCH                        2
BRAZIL                                         TOYOTA                        2
RUSSIA                                         PRESIDENT                     2
VIETNAM                                        MALAYSIA                      2
BELARUS                                        LITHUANIA                     2
BEIJING                                        SRI LANKA                     2
BARACK OBAMA                                   WASHINGTON                    2
VIETNAM                                        PRIME MINISTER                2
RUSSIA                                         KYIV                          2
WASHINGTON                                     ATAL BIHARI VAJPAYEE          2
AUSTRALIA                                      BRUNEI                        2
ATAL BIHARI VAJPAYEE                           WASHINGTON                    2
ASSOCIATION OF SOUTHEAST ASIAN NATIONS         PHNOM PENH                    2
ARMY                                           UNITED STATES                 2
WASHINGTON                                     BARACK OBAMA                  2
RAJASTHAN                                      MINIST                        2
AMBASSADOR                                     VIETNAM                       2
YEMEN                                          COMPANIES                     2
ZAMBIA                                         EUROPEAN COMMISSION           2
CHINA                                          REUTERS                       2
UNITED STATES                                  MAYOR                         2
PRIME MINISTER                                 SRI LANKA                     2
RUSSIA                                         TURKEY                        2
POLICE                                         UNITED STATES                 2
EUROPEAN COMMISSION                            ZAMBIA                        2
SRI LANKA                                      PRIME MINISTER                2
SAN FRANCISCO                                  NEIGHBORHOOD                  2
POPULATION                                     DALLAS                        2
UKRAINIAN                                      UKRAINE                       2
DUTCH COURT                                    MALAYSIA                      2
DUTCH                                          RUSSIA                        2
                                               PRISON                        2
                                               MALAYSIA                      2
DELHI                                          PRIME MINISTER                2
                                               EMPLOYEE                      2
NETHERLANDS                                    MALAYSIA                      2
UNITED NATIONS                                 MOSCOW                        2
COMPANIES                                      YEMEN                         2
UNITED KINGDOM                                 POPULATION                    2
CONGRESS                                       IRELAND                       2
PRIME MINISTER                                 DELHI                         2
UNITED STATES                                  EXXON                         2
                                               COMMUNITY                     2
COMMUNITY                                      CATHOLIC                      2
UNITED STATES                                  BOSS                          2
RUSSIA                                         TAIWAN                        1
SIKH                                           CALIFORNIA                    1
SIOUX                                          COMMUNITY                     1
SECRETARY OF STATE                             PAKISTAN                      1
RUSSIA                                         UKRAINIAN                     1
ROSARIO                                        ROSARIO                       1
SCHOOL                                         SUPREME COURT                 1
                                               UNITED STATES                 1
RUSSIAN                                        UKRAINE                       1
SHANGHAI                                       UZBEKISTAN                    1
RUSSIA                                         VLADIMIR PUTIN                1
A US                                           INTELLIGENCE SERVICE          1
SRI LANKA                                      SPY SHIP                      1
UNITED KINGDOM                                 CHIEF EXECUTIVE               1
                                               MIDI                          1
                                               RUSSIAN                       1
                                               SLOVAK REPUBLIC               1
UNITED STATES                                  HOUSTON                       1
                                               LAWMAKER                      1
                                               LAWYER                        1
                                               MARINES                       1
                                               NEWS OUTLET                   1
                                               PRESIDENT                     1
                                               SCHOOL                        1
UNIVERSITY                                     VOTER                         1
UZBEKISTAN                                     SHANGHAI                      1
VIETNAM                                        FIRST STATE                   1
                                               VIETNAM                       1
VILLAGE                                        POLICE                        1
WEST BENGAL                                    ELECTION COMMISSION           1
YEMENI                                         YEMEN                         1
UNITED KINGDOM                                 FOREIGN SECRETARY             1
UKRAINIAN                                      RUSSIA                        1
SRI LANKAN                                     PRIME MINISTER                1
UKRAINIAN                                      NEWSPAPER                     1
STUDENT                                        UNITED STATES                 1
SUICIDE BOMBER                                 KABUL                         1
SUPREME COURT                                  ALABAMA                       1
TAIWAN                                         CHINA                         1
                                               COMPANY                       1
TALIBAN                                        AFGHAN                        1
TELEVISION                                     LAWMAKER                      1
TEXAS                                          UNITED STATES                 1
THE HAGUE                                      UKRAINE                       1
THE US                                         AMBASSADOR                    1
TOURIST                                        JEREMY HUNT                   1
                                               UNITED KINGDOM                1
TRAVELER                                       HAWAII                        1
                                               UNITED STATES                 1
UKRAINE                                        NEWSPAPER                     1
                                               THE HAGUE                     1
UKRAINIAN                                      IRELAND                       1
RICHMOND                                       UNITED STATES                 1
NEW ZEALAND                                    MINIST OF FOREIGN AFFAIRS     1
RALEIGH                                        COMMERCE DEPARTMENT           1
COMMANDO                                       MEXICO                        1
                                               ROSARIO                       1
COMMUNITY                                      BUSINESS                      1
                                               UNITED STATES                 1
COMPANIES                                      PRESIDENT                     1
CONGRESS                                       BEIJING                       1
                                               CHINA                         1
                                               MILITARY                      1
CRIMINAL                                       NEW YORK                      1
                                               UNITED STATES                 1
DOCTOR                                         SCHOOL                        1
                                               STUDENT                       1
DUTCH COURT                                    PRISON                        1
EGYPT                                          JAKARTA                       1
EGYPTIAN                                       JAKARTA                       1
ELECTION COMMISSION                            WEST BENGAL                   1
EUROPEAN                                       EUROPEAN                      1
FIRST STATE                                    VIETNAM                       1
FLORIDA                                        STUDENT                       1
FOREIGN SECRETARY                              INTELLIGENCE                  1
                                               UNITED KINGDOM                1
FRENCH                                         BRUNEI                        1
                                               CHINA                         1
GERMAN                                         SCHOOL                        1
COMMANDO                                       PRISONER                      1
COLLEGE                                        BUSINESS                      1
GHANA                                          MINIST                        1
CITIZEN                                        STUDENT                       1
ACTOR                                          UNITED KINGDOM                1
AL QAEDA                                       MILITIA                       1
AMBASSADOR                                     AUSTRIA                       1
ARBIL                                          KURD                          1
ARMY                                           KING                          1
AUSTRALIA                                      PARLIAMENT HOUSE              1
AUSTRALIAN                                     BRUNEI                        1
                                               CHINA                         1
BANK OF AMERICA                                UNITED STATES                 1
BOSS                                           UNITED STATES                 1
BRATISLAVA                                     LONDON                        1
BRAZIL                                         AFRICA                        1
BULGARIAN                                      MILITARY                      1
BUSINESS                                       COLLEGE                       1
CALIFORNIA                                     CONGRESSMAN                   1
CANADA                                         PRIEST                        1
                                               ROMAN CATHOLIC                1
CAPTAIN                                        COMPANY                       1
CHINA                                          BUSINESS                      1
                                               COMPANY                       1
                                               MINIST OF EDUCATION           1
                                               PHNOM PENH                    1
CITIZEN                                        LIBERIA                       1
GHANA                                          JOURNALIST                    1
GOVERNMENT                                     NIGERIAN                      1
QUEEN ELIZABETH II                             PRINCE                        1
ACCRA                                          JOURNALIST                    1
OPPOSITION LEADER                              PAKISTAN                      1
ORGANIZATION OF PETROLEUM EXPORTING COUNTRIES  AMERICAN                      1
PAKISTAN                                       PRIME MINISTER                1
PALESTINE                                      TURKEY                        1
PALESTINIAN                                    ISRAELI                       1
PARLIAMENT HOUSE                               AUSTRALIA                     1

In [42]:
get_single_entity_group(result_2022_df, 'Actor1KnownGroupCode', 'GlobalEventID')

Actor1KnownGroupCode
EEC    9
UNO    5
ASN    2
ALQ    1
OPC    1
TAL    1
Name: GlobalEventID, dtype: int64

In [43]:
get_single_entity_group(result_2022_df, 'Actor1EthnicCode', 'GlobalEventID')
# result_2022_df.groupby(['Actor1EthnicCode'])['GlobalEventID'].count().sort_values(ascending=False)

Actor1EthnicCode
kur    5
dak    3
iku    2
Name: GlobalEventID, dtype: int64

In [44]:
get_single_entity_group(result_2022_df, 'Actor1Religion1Code', 'GlobalEventID')
# result_2022_df.groupby(['Actor1Religion1Code'])['GlobalEventID'].count().sort_values(ascending=False)

Actor1Religion1Code
SIK    3
CHR    2
MOS    1
Name: GlobalEventID, dtype: int64

In [45]:

get_single_entity_group(result_2022_df, 'Actor1Religion2Code', 'GlobalEventID')
# result_2022_df.groupby(['Actor2Religion1Code'])['GlobalEventID'].count().sort_values(ascending=False)

Actor1Religion2Code
CTH    2
Name: GlobalEventID, dtype: int64

In [46]:
get_single_entity_group(result_2022_df, 'Actor1Type1Code', 'GlobalEventID')

Actor1Type1Code
GOV    113
COP     29
CVL     27
JUD     23
BUS     19
IGO     17
LEG     16
EDU     16
MIL     10
MNC      8
MED      7
SEP      5
OPP      5
SPY      5
ELI      4
HLH      4
NGO      3
AGR      3
LAB      3
UAF      3
CRM      2
INS      1
REB      1
IMG      1
Name: GlobalEventID, dtype: int64

In [47]:
get_single_entity_group(result_2022_df, 'Actor2Type1Code', 'GlobalEventID')

Actor2Type1Code
GOV    100
BUS     35
CVL     28
COP     25
LEG     17
EDU     16
MIL      9
MNC      8
MED      8
CRM      7
ELI      6
SPY      6
LAB      6
JUD      5
IGO      5
OPP      4
UAF      1
Name: GlobalEventID, dtype: int64

In [48]:
get_single_entity_group(result_2022_df, 'IsRootEvent', 'GlobalEventID')

IsRootEvent
1    456
0    376
Name: GlobalEventID, dtype: int64

In [49]:
get_single_entity_group(result_2022_df, 'EventCode', 'GlobalEventID')

EventCode
42      107
43       90
173      51
10       50
190      43
20       34
40       25
90       25
51       24
112      24
71       23
17       21
36       19
120      19
13       19
46       17
193      16
111      16
141      15
110      15
12       14
50       12
70        9
73        9
60        9
874       9
100       8
57        8
15        8
172       7
84        5
61        5
80        5
180       4
1821      4
14        4
31        3
138       3
1041      3
1712      3
181       3
160       3
150       3
831       3
41        3
45        3
53        3
130       2
125       2
115       2
28        2
1822      2
22        2
72        2
32        2
1823      1
1124      1
81        1
311       1
231       1
23        1
166       1
102       1
64        1
1831      1
Name: GlobalEventID, dtype: int64

In [50]:
get_single_entity_group(result_2022_df, 'EventRootCode', 'GlobalEventID')

EventRootCode
4     245
1     116
17     61
19     59
11     58
5      47
7      43
2      40
9      25
3      25
8      23
12     21
6      15
14     15
18     15
10     12
13      5
16      4
15      3
Name: GlobalEventID, dtype: int64

In [51]:
get_single_entity_group(result_2022_df, 'QuadClass', 'GlobalEventID')

QuadClass
1    473
4    142
3    111
2    106
Name: GlobalEventID, dtype: int64